version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - "pymedphys dev docs --prep"

python:
  install:
    - requirements: requirements-docs.txt

sphinx:
  builder: html
  fail_on_warning: false
  configuration: lib/pymedphys/docs/conf.py
